// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfrNrrcam1yyRn3KB4W8PUEyla3ws7JhA',
    appId: '1:791848024762:web:3a84948c1d78d123b02083',
    messagingSenderId: '791848024762',
    projectId: 'humacare-bfcbb',
    authDomain: 'humacare-bfcbb.firebaseapp.com',
    storageBucket: 'humacare-bfcbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ol5cXdTbrZU6roeGZ1nMgLiL0xMjeqI',
    appId: '1:791848024762:android:831ed799eef1ca78b02083',
    messagingSenderId: '791848024762',
    projectId: 'humacare-bfcbb',
    storageBucket: 'humacare-bfcbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbIjsAJs73EwVm6pytEPPPyB9kjfmfLls',
    appId: '1:791848024762:ios:bb37c44f646cb6d2b02083',
    messagingSenderId: '791848024762',
    projectId: 'humacare-bfcbb',
    storageBucket: 'humacare-bfcbb.appspot.com',
    iosClientId: '791848024762-jdfrki3eunuupjsl8118s65j7dkpc9v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbIjsAJs73EwVm6pytEPPPyB9kjfmfLls',
    appId: '1:791848024762:ios:bb37c44f646cb6d2b02083',
    messagingSenderId: '791848024762',
    projectId: 'humacare-bfcbb',
    storageBucket: 'humacare-bfcbb.appspot.com',
    iosClientId: '791848024762-jdfrki3eunuupjsl8118s65j7dkpc9v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoire',
  );
}
